# Generated by Django 5.2 on 2025-06-10 05:40

import django.contrib.postgres.fields
import generators.ulid
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        BtreeGinExtension(),
        migrations.CreateModel(
            name="AuthorizationCode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "id",
                    models.CharField(
                        default=generators.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("code", models.CharField(max_length=255, unique=True)),
                ("redirect_uri", models.TextField()),
                ("scope", models.TextField()),
                ("nonce", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "code_challenge",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "code_challenge_method",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "id",
                    models.CharField(
                        default=generators.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=100, unique=True)),
                (
                    "client_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("client_name", models.CharField(max_length=200)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("confidential", "Confidential"),
                            ("public", "Public"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "redirect_uris",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        help_text="Comma separated URIs",
                        size=None,
                    ),
                ),
                (
                    "scope",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        help_text="Scopes that the client can request",
                        size=None,
                    ),
                ),
                ("require_pkce", models.BooleanField(default=False)),
                (
                    "allowed_grant_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        help_text="Allowed grant types for the client",
                        size=None,
                    ),
                ),
                ("jwks_uri", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "id",
                    models.CharField(
                        default=generators.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("access_token", models.CharField(max_length=255, unique=True)),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("token_type", models.CharField(default="Bearer", max_length=20)),
                ("scope", models.TextField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
