# Generated by Django 5.2 on 2025-06-09 07:08

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_client_authorizationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorizationcode",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[("animecore", "AnimeCore"), ("public", "Public")],
                default="confidential",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="scope",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                default=["openid", "profile", "email"],
                help_text="Scopes that the client can request",
                size=None,
            ),
        ),
    ]
